query GetGlobals {
  SiteSettings {
    typography {
      font
      fontSize
    }
    colors {
      background
      foreground
      primary
      primaryForeground
      secondary
      secondaryForeground
      muted
      mutedForeground
      border
      accent
      accentForeground
    }
    navbar {
      textColor
      backgroundColor
      backgroundColorScroll
      logo {
        ...SVG
      }
      links {
        label
        url
        openInNewTab
      }
      buttons {
        ...Button
      }
    }
    footer {
      links {
        label
        url
        openInNewTab
      }
    }
    meta {
      title
      description
      image {
        ...Image
      }
    }
  }
}