query GetHomePage {
  TemplatePages(limit: 1, where: { template: { equals: Home } }) {
    docs {
      ...TemplatePage
      homeTemplateFields {
        myTextField
        layout {
          ... on HeroBlock {
            blockType
            title
            subtitle
            image {
              ...Image
            }
            cta {
              label
              url
            }
          }
          ... on TextBlock {
            blockType
            content
          }
        }
      }
    }
  }
}